Provide libicuuc to linker
Building YAZ on openSUSE Tumbleweed failed with this error when linking "yaz-icu":

undefined reference to symbol 'ucnv_getDefaultName_76'
/usr/lib64/libicuuc.so.76: error adding symbols: DSO missing from command line

As far as I understand it the linker wants to have the transitive dependency made explicit and adding it to the m4 config seemed liked the earliest possible opportunity to achieve that goal.